### ISSUE TITLE
why

### ISSUE THREAD

**Issue by MeetPing** [The-SourceCode/Discord.js-Bot-Development#12]
ur code sucks so do u cuz u banned me from the sourcecode but why let the let command is fing sucks cuz when i tried it aint know wha it is

**Comment by ersu98** [comment]
lol

**Comment by MeetPing** [comment]
Nah

**Comment by MuchaDiscord** [comment]
close this ,please.

**Comment by MeetPing** [comment]
nah

**Comment by jackmaster9000** [comment]
this is sad

**Comment by MeetPing** [comment]
i thought thesource codes was someohter server sorry i will close this tho
