### ISSUE TITLE
/opt/watcher/app-types/node/start.sh: line 43: null: command not found   /opt/watcher/app-types/node/start.sh: line 43: null: command not found

### ISSUE THREAD

**Issue by MeetPing** [The-SourceCode/Discord.js-Bot-Development#14]
/opt/watcher/app-types/node/start.sh: line 43: null: command not found

/opt/watcher/app-types/node/start.sh: line 43: null: command not found

**Comment by The-SourceCode** [comment]
Hi @MeetPing ,

We're going to need more information than this.
