### ISSUE TITLE
Error in warnlevel.js

### ISSUE THREAD

**Issue by Turdant** [The-SourceCode/Discord.js-Bot-Development#15]
If there are no warnings in warnings.json then there will be an error in the console.
To fix this change the warnlevel.js into this:
`
const Discord = require("discord.js");
const fs = require("fs");
const ms = require("ms");
let warns = JSON.parse(fs.readFileSync("./warnings.json", "utf8"));

module.exports.run = async (bot, message, args) => {

  if(!warns.warns) {
    message.channel.send(new Discord.RichEmbed()
          .setDescription("There are no warnings")
    );
    return;
  };
  if(!message.member.hasPermission("MANAGE_MESSAGES")) return message.reply("You can't do that.");
  let wUser = message.guild.member(message.mentions.users.first()) || message.guild.members.get(args[0])
  if(!wUser) return message.reply("Couldn't find them yo");
  let warnlevel = warns[wUser.id].warns;

  message.channel.send(new Discord.RichEmbed()
        .setDescription("Warning Information")
        .setColor("#c40000")
        .addField("Member", `<@${wUser.id}>`)
        .addField("Amount of Warns", warnlevel)
  );
}

module.exports.help = {
  name: "warnlevel"
}
`

**Comment by The-SourceCode** [comment]
Yeah when recording I forgot to include this snip of code to check for that. I haven't tried yours but I assume it works, but it could also be done using the same code used for `warn.js`.
```JS
 if(!warns[wUser.id]) warns[wUser.id] = {
    warns: 0
  };
