### ISSUE TITLE
idea kinda

### ISSUE THREAD

**Issue by MeetPing** [The-SourceCode/Discord.js-Bot-Development#16]
just make them all like the same so we get it like in the tutorial videos

**Comment by acollierr17** [comment]
Just to piggyback off this. I would make each episode its own branch. Each branch has the full files used in that episode. There, it would make things *a lot* easier when people come to this repo.

**Comment by MeetPing** [comment]
what about there is one folder with all of the code so i can ust use that and test it on another bot so i can see if i ould implement code to my bot

**Comment by acollierr17** [comment]
> what about there is one folder with all of the code so i can ust use that and test it on another bot so i can see if i ould implement code to my bot

Personally, I would think it'd be easier to navigate each episode via its own branch. Because like I said, you can go to the branch for a specific episode and see all the code from that episode. Not just a single command file or two from how it's already laid out.

**Comment by SloRunner** [comment]
i would agree with branching this off, also it does not take that much time and it can have full files in it

**Comment by The-SourceCode** [comment]
Yeah I know. I shoulda done this from the beginning. I just wasn't crazy about Github back then. I'll try this for the next episode. :)
