### ISSUE TITLE
doesnt have the json files and idk how to make them please help me out

### ISSUE THREAD

**Issue by XanaxModding** [The-SourceCode/Discord.js-Bot-Development#3]

**Comment by BreakingCodes** [comment]
Did you install the discord.js at all? We're gonna need more information than that.

**Comment by vampymaria** [comment]
Er ... run "npm init -y" in your folder ;-; assuming you know how to do so ... And for gods sake dont add the quotations in the command in your cmd/powershell

**Comment by MilkLegend** [comment]
I suggest you to learn Discord.js

**Comment by RazorApple** [comment]
1. learn d.js
2. Get the files at **[github.com/razorapple/pBot](https://github.com/razorapple/pBot)**
3. Change the token.
4. Run the bot
A very not-clear guide. Please learn d.js.

**Comment by yossef01102015** [comment]
Learn JavaScript,node.js, first before trying to learn discord.js
