### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined - Episode 2

### ISSUE THREAD

**Issue by Ariikitty** [The-SourceCode/Discord.js-Bot-Development#39]
I'm extremely new to JavaScript and Node.js so this could just be me being unaware of something but I am having an issue with the say command. When ever I try to use the command, the command message deletes fine but the bot doesn't send a message at all. When checking the logs, I have this error.

I have tried checking over the code for the bot and even gone as far as copying the code from this repo but to no avail so if someone knows what I may be doing wrong or needs some more info then let me know :)

**Comment by Ariikitty** [comment]
Alright so further testing shows that it's only if I send {prefix}say that it doesn't working which is weird because there's a line that should catch that and reply with "Nothing to say?" so I'm not sure what's happening there but other then that it's all good

**Comment by PantheraRed** [comment]
Perhaps sending your code will give us a better idea about what we are dealing with here. Some screenshots and examples would be neat. :+1:

**Comment by Ariikitty** [comment]
Old issue, forgot to say but I have solved the issue and have only just noticed the issue was still open
