### ISSUE TITLE
Request for pay system

### ISSUE THREAD

**Issue by GamersLeo** [The-SourceCode/Discord.js-Bot-Development#4]
Could you please add in something to check if the user that is getting the coins is not the user who sent it?

**Comment by Xirez** [comment]
Just add it yourself dude.. it's really not that hard.
Just do a validation of what the user id is that sends the money and then the id of the one getting it.

if(pUser.id === message.author.id){
        return message.reply("Cant send money to yourself!");
    }

As an example using his code and json file.

**Comment by GamersLeo** [comment]
Thanks, but I already found a it out 2 weeks ago.
