### ISSUE TITLE
SyntaxError: Identifier 'client' has already been declared

### ISSUE THREAD

**Issue by Spo0kkyy** [The-SourceCode/Discord.js-Bot-Development#42]
I don't know why but it says "SyntaxError: Identifier 'client' has already been declared" for ep. 1 where the code says "const client = new Client({ <=
and i don't know what's wrong or anything.
![image](https://user-images.githubusercontent.com/59513841/76169010-d1968c00-614a-11ea-91b4-3fe65737d57b.png)

**Comment by Spo0kkyy** [comment]
Fixed

**Comment by Riley399** [comment]
> Fixed

how do i fix this problem pal
