### ISSUE TITLE
where is the `clearReactions` function defined?

### ISSUE THREAD

**Issue by saatvikn** [The-SourceCode/Discord.js-Bot-Development#54]
https://github.com/The-SourceCode/Discord.js-Bot-Development/tree/master/Ep_08

**Comment by Bloectasy** [comment]
clearReactions is a thing in d.js v11use reactions.remove for d.js v12 instead

**Comment by saatvikn** [comment]
ok let me see

**Comment by Rayne231** [comment]
![image](https://user-images.githubusercontent.com/69247113/90633850-6ea23880-e244-11ea-98a3-2f60bee02829.png)
i changed it to that the command is working now but the reactions are still not removed
