### ISSUE TITLE
where are the cat and dog commands

### ISSUE THREAD

**Issue by stijn2005** [The-SourceCode/Discord.js-Bot-Development#6]
where are the cat and dog commands

**Comment by PantheraRed** [comment]
Put this inside index.js :- 
if(cmd === `${prefix}cat`) {
		try {
			get('https://aws.random.cat/meow').then(res => {
				return message.channel.send({files: [{attachment: response.body.file, name: `cat.${response.body.file.split('.')[2]}`}]});
			});
		} catch(err) {
			return msg.channel.send(error.stack);
		}
	}
});
In case you are using separate "commands" file like "cat.js" then try :- 
const Discord = require("discord.js");

module.exports.run = async (bot, message, args) => {
		try {
			get('https://aws.random.cat/meow').then(res => {
				return message.channel.send({files: [{attachment: response.body.file, name: `cat.${response.body.file.split('.')[2]}`}]});
			});
		} catch(err) {
			return msg.channel.send(error.stack);
		}
	}
});
}

module.exports.help = {
  name: "cat"
}
